FROM python:3.8-slim
WORKDIR /app
COPY . /app
RUN pip install --no-cache-dir -r requirements.txt
RUN pip install "fastapi[standard]"
EXPOSE 8000
CMD ["fastapi", "dev", "app.py", "--host", "0.0.0.0", "--port", "8000"]
